### ISSUE TITLE
status bar color is not change in dark mode

### ISSUE THREAD

**Issue by Prashant4900** [anfeichtinger/flutter_production_boilerplate#2]
![WhatsApp Image 2021-06-20 at 12 10 12 AM](https://user-images.githubusercontent.com/62440911/122652342-fe15c200-d15b-11eb-936c-f3e367dc2325.jpeg)

`
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      darkTheme: AppThemes.darkTheme,
      theme: AppThemes.lightTheme,
      themeMode: ThemeMode.system,
      home: Wrapper(),
      builder: EasyLoading.init(),
    );
  }
}

`

**Comment by reafeichtinger** [comment]
For changing the Statusbar (Icon) color I'm using the AppBarGone Widget as the Scaffolds appBar. I found this the most reliable way to get it working and I always use a custom AppBar in my applications. This method works for API 23+.

    return Scaffold(

        // This!
        appBar: const AppBarGone(),

        body: AnimatedSwitcher(
            duration: const Duration(milliseconds: 300),
            child: _pageNavigation.elementAt(state)),
        bottomNavigationBar: BottomNavBar(),
    );

**Comment by Prashant4900** [comment]
> For changing the Statusbar (Icon) color I'm using the AppBarGone Widget as the Scaffolds appBar. I found this the most reliable way to get it working and I always use a custom AppBar in my applications. This method works for API 23+.
> 
> ```
> return Scaffold(
> 
>     // This!
>     appBar: const AppBarGone(),
> 
>     body: AnimatedSwitcher(
>         duration: const Duration(milliseconds: 300),
>         child: _pageNavigation.elementAt(state)),
>     bottomNavigationBar: BottomNavBar(),
> );
> ```

but what about when I don't have any app bar

**Comment by reafeichtinger** [comment]
I think you are misunderstanding. It is called AppBarGone because it is not actually an AppBar. If you look at the screenhots at the bottom of the Readme file you can see how it looks in the UI. Please note that the Appbar  does not contain the header text, it is literally just the colored statusbar in this case. Also have a look at how the Widget is implemented.

- [Screenshot](https://github.com/anfeichtinger/flutter_production_boilerplate/blob/master/assets/img/home_dark.png)
- [AppBarGone](https://github.com/anfeichtinger/flutter_production_boilerplate/blob/master/lib/ui/widgets/app_bar_gone.dart)

**Comment by Prashant4900** [comment]
> I think you are misunderstanding. It is called AppBarGone because it is not actually an AppBar. If you look at the screenhots at the bottom of the Readme file you can see how it looks in the UI. Please note that the Appbar does not contain the header text, it is literally just the colored statusbar in this case. Also have a look at how the Widget is implemented.
> 
> * [Screenshot](https://github.com/anfeichtinger/flutter_production_boilerplate/blob/master/assets/img/home_dark.png)
> * [AppBarGone](https://github.com/anfeichtinger/flutter_production_boilerplate/blob/master/lib/ui/widgets/app_bar_gone.dart)

ok thanks 
so I just need this app bar on every page

**Comment by reafeichtinger** [comment]
> ok thanks
so I just need this app bar on every page

Basically yes. You'll need it for every Scaffold where you want that specific behaviour. 

I don't use a separate Scaffold for the pages of the bottom navigation bar.
I do use a separate Scaffold when pushing a different screen, e.g with `Navigator.of(context).push(...);`
