### ISSUE TITLE
Bottom Navigation Bar not display correct selected item

### ISSUE THREAD

**Issue by hongquan** [anfeichtinger/flutter_production_boilerplate#3]
When I tab to the 2nd item in the bottom navigation bar, its color is not changed.
![Screenshot_20220222-095636](https://user-images.githubusercontent.com/314607/155055159-68828cf0-7189-4dbe-a65d-2e22ae03a878.png)
.

**Comment by reafeichtinger** [comment]
Seems like an update to the flutter framework broke this. I've pushed a quick fix so it should now work properly. Give it a try and reopen this if it is still not working properly.
